# Generated by Django 4.2.11 on 2024-09-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_no', models.IntegerField()),
                ('e_name', models.CharField(max_length=64)),
                ('e_salary', models.IntegerField()),
                ('e_addr', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
